import openmm.app as app
import openmm as om
from openff.toolkit.topology import Molecule, Topology
from openmmforcefields.generators import SystemGenerator
import parmed
import os
import openmm.unit as unit 
import numpy as np # Needed for array manipulation

# --- Configuration ---
# File generated by PACKMOL
INPUT_PDB = 'system_coordinates.pdb' 
# The latest production OpenFF Force Field
OPENFF_FF = 'openff-2.2.0.offxml' # Sage
# Standard water model
WATER_FF = 'tip3p.xml' 

# Atom counts for identification: C18H35O2- (18C + 2O + 35H = 55 atoms)
STEARATE_ATOMS = 55
SODIUM_ATOMS = 1
WATER_ATOMS = 3

def parameterize_and_create_system(pdb_file_path):
    """
    Reads the system coordinates, separates solute and solvent, 
    parameterizes the solute using OpenFF (in-memory), and combines with solvent using Modeller.
    
    The function generates a ready-to-use OpenMM System object.
    """
    print(f"--- 1. Loading coordinates from {pdb_file_path} ---")
    if not os.path.exists(pdb_file_path):
        print(f"ERROR: PDB file not found at {pdb_file_path}. Please check your path.")
        return None, None, None

    # Load the structure using ParmEd to get coordinates and a basic structure
    try:
        full_structure = parmed.load_file(pdb_file_path)
    except Exception as e:
        print(f"Error loading PDB file with ParmEd: {e}")
        return None, None, None

    # Load the PDB into an OpenMM PDBFile object for full atom and residue lists
    pdb_file_obj = app.PDBFile(pdb_file_path)
    openmm_topology_input = pdb_file_obj.topology
    full_openmm_positions = pdb_file_obj.getPositions() # OpenMM coordinates
    
    # --- 2. Define Solute Molecules using SMILES ---
    stearate_ion_smiles = "CCCCCCCCCCCCCCCCCC(=O)[O-]"
    sodium_ion_smiles = "[Na+]"
    
    stearate_ion = Molecule.from_smiles(stearate_ion_smiles, allow_undefined_stereo=True)
    sodium_ion = Molecule.from_smiles(sodium_ion_smiles, allow_undefined_stereo=True)
    
    # Explicitly name the OpenFF molecules to help matching
    stearate_ion.name = "STL" 
    sodium_ion.name = "NA"
    
    unique_solute_molecules = [stearate_ion, sodium_ion]
    
    # --- 3. Identify and Separate Solute and Solvent Atom Indices ---
    print("--- 2. Separating Solute (STL, NA) and Solvent (HOH) ---")
    
    solute_atom_indices = []
    stearate_count = 0
    sodium_count = 0
    
    # Manually iterate over ParmEd structure residues to identify and collect solute indices
    for residue in full_structure.residues:
        num_atoms = len(residue.atoms)
        if num_atoms == STEARATE_ATOMS:
            solute_atom_indices.extend([atom.idx for atom in residue.atoms])
            stearate_count += 1
        elif num_atoms == SODIUM_ATOMS:
            solute_atom_indices.extend([atom.idx for atom in residue.atoms])
            sodium_count += 1
    
    # --- 4. Generate Corrected Solute Topology (in-memory) ---
    print("--- 3. Generating Corrected Solute Topology via OpenFF (in-memory) ---")
    
    # 4a. Create a list of the intended solute molecules in the correct order 
    # (matching the order of indices collected above).
    ordered_solute_molecules = ([stearate_ion] * stearate_count) + ([sodium_ion] * sodium_count)
    
    # 4b. Use OpenFF to create a guaranteed correct OpenFF Topology from the ordered molecules.
    openff_solute_topology = Topology.from_molecules(ordered_solute_molecules)

    # 4c. Convert the fixed OpenFF Topology back to an OpenMM Solute Topology.
    fixed_openmm_solute_topology = openff_solute_topology.to_openmm()
    
    # 4d. Extract the solute positions in the same order as the indices were collected
    solute_positions_nm = []

    # Deterministic coordinate handling: assume PACKMOL wrote coordinates in
    # Angstroms (the common default). Read positions as Angstroms and convert
    # to nanometers by multiplying by 0.1. This removes the need for heuristics.
    raw_positions = full_openmm_positions
    try:
        if hasattr(raw_positions, 'value_in_unit'):
            full_coords_ang = np.array(raw_positions.value_in_unit(unit.angstroms))
        else:
            # raw_positions is an iterable of Vec3-like objects (numbers are Angstroms)
            full_coords_ang = np.array([[p.x, p.y, p.z] for p in raw_positions], dtype=float)
    except Exception:
        # Best-effort fallback
        full_coords_ang = np.array([[getattr(p, 'x', p[0]), getattr(p, 'y', p[1]), getattr(p, 'z', p[2])] for p in raw_positions], dtype=float)

    # Convert Angstrom -> nanometer deterministically
    full_coords_nm = full_coords_ang * 0.1

    for idx in solute_atom_indices:
        # Append the array [x, y, z] for the solute atom
        solute_positions_nm.append(full_coords_nm[idx])

    # Convert the list of unit-less coordinates to a NumPy array and apply the unit
    solute_positions_array = np.array(solute_positions_nm) * unit.nanometers
    
    # --- 5. Rebuild Full System Topology using Modeller ---
    print("--- 4. Rebuilding Full System Topology with Fixed Solute and Water ---")
    
    # Initialize Modeller with the fixed solute topology and positions
    modeller = app.Modeller(fixed_openmm_solute_topology, solute_positions_array)
    
    # --- Water: validate that PACKMOL output uses TIP3P-compatible naming ---
    # We'll rely on the TIP3P template in the force field to set up rigid water.
    # Therefore the PDB must contain residues named HOH (or WAT/H2O) with atom
    # names O, H1, H2. If this is not the case, fail early with instructions.
    water_positions_list = []
    water_count = 0

    bad_waters = []
    # Map of old atom index -> position (nm)
    index_to_pos = {i: full_coords_nm[i] for i in range(len(full_coords_nm))}

    for res in openmm_topology_input.residues():
        if (res.name or '').strip().upper() in ('HOH', 'WAT', 'H2O'):
            water_count += 1
            atom_names = [atom.name for atom in res.atoms()]
            # Expect exactly O, H1, H2 (order may vary). If not found, mark bad.
            if not all(n in atom_names for n in ('O', 'H1', 'H2')):
                bad_waters.append((res.id, atom_names))
            else:
                # Collect positions in residue atom order
                for atom in res.atoms():
                    water_positions_list.append(index_to_pos[atom.index])

    if bad_waters:
        print('\nERROR: Found water residues that are not TIP3P-compatible.')
        print('Examples (residue id, atom names):')
        for rid, names in bad_waters[:5]:
            print(f'  {rid}: {names}')
        print('\nPlease ensure your water monomer PDB uses residue name HOH (or WAT/H2O)')
        print("and atom names 'O', 'H1', 'H2' so the TIP3P template can be applied.")
        print('Alternatively, adjust the monomer PDBs produced by builder.py to match these conventions.')
        return None, None, None

    # Convert to positions array (nm)
    water_positions_array = np.array(water_positions_list) * unit.nanometers

    # Add the waters to the Modeller using the canonical HOH topology we constructed
    # Build a minimal water topology from the input topology (preserving residue ids)
    water_topology = app.Topology()
    water_chain = water_topology.addChain()
    old_to_new = {}
    for res in openmm_topology_input.residues():
        if (res.name or '').strip().upper() in ('HOH', 'WAT', 'H2O'):
            new_res = water_topology.addResidue('HOH', water_chain, res.id)
            for atom in res.atoms():
                new_atom = water_topology.addAtom(atom.name, atom.element, new_res, atom.id)
                old_to_new[atom.index] = new_atom

    # Add only internal O-H bonds for each water residue (do NOT copy inferred
    # bonds from the PACKMOL/ParmEd topology: those may include external
    # contacts and will break the TIP3P template matching).
    for res in openmm_topology_input.residues():
        if (res.name or '').strip().upper() in ('HOH', 'WAT', 'H2O'):
            # find the corresponding new residue by residue id
            # Note: we added residues in the same order and used the same res.id
            # when creating new_res above, so we can look up atoms by their
            # names in old_to_new mapping.
            atom_names = [atom.name for atom in res.atoms()]
            if all(n in atom_names for n in ('O', 'H1', 'H2')):
                # map names to atom indices to find new atoms
                name_to_oldidx = {atom.name: atom.index for atom in res.atoms()}
                aO = old_to_new[name_to_oldidx['O']]
                aH1 = old_to_new[name_to_oldidx['H1']]
                aH2 = old_to_new[name_to_oldidx['H2']]
                water_topology.addBond(aO, aH1)
                water_topology.addBond(aO, aH2)

    print(f"Adding {water_count} water residues to the system (TIP3P-compatible).")
    modeller.add(water_topology, water_positions_array)

    # There are no manual constraints added anymore; SystemGenerator should
    # apply TIP3P rigid-water handling. Keep track that we did not add
    # constraints programmatically.
    constraints_added = 0
    
    # Final Topology and Positions
    full_openmm_topology = modeller.topology
    final_positions = modeller.positions
    
    # --- 6. Prepare Final Topology (Renaming Residues for SystemGenerator) ---
    print("--- 5. Preparing Final Topology (Renaming Residues for SystemGenerator) ---")
    
    # Explicitly rename residues on the full OpenMM topology object. Prefer
    # residue name when available, otherwise fall back to atom-count heuristics.
    current_stearate = 0
    current_sodium = 0
    current_water = 0

    for chain in full_openmm_topology.chains():
        for residue in chain.residues():
            num_atoms = len(list(residue.atoms()))
            name = (residue.name or '').strip().upper()

            if name in ('STL', 'STEARATE') or num_atoms == STEARATE_ATOMS:
                residue.name = 'STL'
                current_stearate += 1
            elif name in ('NA',) or num_atoms == SODIUM_ATOMS:
                residue.name = 'NA'
                current_sodium += 1
            elif name in ('HOH', 'WAT', 'H2O') or num_atoms == WATER_ATOMS:
                residue.name = 'HOH'
                current_water += 1

    print(f"Renamed/identified {current_stearate} Stearate (STL), {current_sodium} Sodium (NA), {current_water} Water (HOH) residues in topology.")

    # --- 7. Initialize Final System Generator ---
    print("--- 6. Initializing Final System Generator ---")
    print(f"Using Solute FF: {OPENFF_FF}")
    print(f"Using Solvent FF: {WATER_FF}")
    
    # Final System Generator (handles combining FFs and water models)
    final_generator = SystemGenerator(
        forcefields=[WATER_FF], 
        small_molecule_forcefield=OPENFF_FF,
        molecules=unique_solute_molecules,
    )
    
    # --- 8. Create the final OpenMM System ---
    print("--- 7. Generating OpenMM System with parameters (This may take a moment) ---")
    
    # Generate the FINAL OpenMM System using the clean, full topology with no extra arguments
    openmm_system = final_generator.create_system(
        full_openmm_topology, # Use the OpenFF-corrected and Modeller-rebuilt topology
    )
    
    # Rely on SystemGenerator / the TIP3P template to add rigid-water handling
    # (SETTLE or equivalent). We validated residue/atom naming earlier so this
    # should be applied automatically by the force field generator.


    # --- 9. Manually Apply Missing Simulation Settings ---
    print("--- 8. Manually applying PME and Box Vectors to the OpenMM System ---")
    
    # The box vectors must be set manually since the PDB does not contain them
    # Based on PACKMOL box size (110.0 Angstroms = 11.0 nm)
    box_size_nm = 11.0
    box_vector = om.Vec3(box_size_nm * unit.nanometers, 0, 0)
    openmm_system.setDefaultPeriodicBoxVectors(
        box_vector,
        om.Vec3(0, box_vector[0], 0),
        om.Vec3(0, 0, box_vector[0])
    )
    
    print("\n✅ Final System Parameterization Complete.")
    print("The OpenMM System object is ready for simulation.")
    
    # --- 10. Saving Final PDB coordinates ---
    # We save a final PDB file which can be used alongside the OpenMM System object
    with open('openmm_system.pdb', 'w') as f:
        # Use the final topology and positions from the Modeller
        app.PDBFile.writeFile(full_openmm_topology, final_positions, f, keepIds=True)

    print("Files saved:")
    print("- openmm_system.pdb (Initial coordinates for the OpenMM simulation)")

    # Some basic validation checks on the final OpenMM System
    print('\n--- Running basic validation checks ---')

    # 1) Check nonbonded force and total system charge
    net_charge = None
    for f in openmm_system.getForces():
        if isinstance(f, om.NonbondedForce):
            total_q = 0.0
            for i in range(f.getNumParticles()):
                q, sig, eps = f.getParticleParameters(i)
                # q may be a Quantity; attempt to extract a numeric value
                try:
                    total_q += q._value
                except Exception:
                    try:
                        total_q += float(q)
                    except Exception:
                        total_q += 0.0
            # q is in units of elementary charge; wrap with unit
            try:
                net_charge = total_q * unit.elementary_charge
            except Exception:
                net_charge = total_q
            break

    if net_charge is not None:
        try:
            netq = net_charge.value_in_unit(unit.elementary_charge)
        except Exception:
            netq = float(net_charge)
        print(f"Total system charge (approx): {netq:.6f} e")
        if abs(netq) > 1e-6:
            print("Warning: system total charge is non-zero. Check ion counts or charges.")
    else:
        print("Warning: NonbondedForce not found in system; cannot compute total charge.")

    # 2) Check that the number of constraints roughly matches expected water constraints
    num_constraints = openmm_system.getNumConstraints()
    print(f"Total constraints in system: {num_constraints}")
    if constraints_added and num_constraints != constraints_added:
        print(f"Note: constraints_added={constraints_added} but system reports {num_constraints}.")

    # The GROMACS export section has been removed as it is not needed for OpenMM.
    # We return the key objects required for an OpenMM simulation run:
    return openmm_system, full_openmm_topology, final_positions

if __name__ == "__main__":
    
    # Check for required dependencies
    try:
        import openmmforcefields
        import parmed
        import numpy
    except ImportError:
        print("\nFATAL ERROR: The 'openmmforcefields', 'parmed', and 'numpy' packages are required.")
        print("Please install them: conda install -c conda-forge openmm openmmforcefields parmed numpy")
        exit()

    # The main function now returns the OpenMM objects directly
    openmm_system, openmm_topology, initial_positions = parameterize_and_create_system(INPUT_PDB)

    print("\n--- NEXT STEP: Run the OpenMM Simulation ---")
    print("The Python script has successfully generated the key objects:")
    print("1. 'openmm_system': The OpenMM System with all forces and parameters.")
    print("2. 'openmm_topology': The OpenMM Topology with residue/atom names.")
    print("3. 'initial_positions': The initial coordinates.")
    print("You can now use these objects to create an Integrator and Simulation object in OpenMM.")