import openmm.app as app
import openmm as om
from openff.toolkit.topology import Molecule, Topology
from openmmforcefields.generators import SystemGenerator
import parmed
import os
import openmm.unit as unit 
import numpy as np # Needed for array manipulation

# --- Configuration ---
# File generated by PACKMOL
INPUT_PDB = 'system_coordinates.pdb' 
# The latest production OpenFF Force Field
OPENFF_FF = 'openff-2.2.0.offxml' # Sage
# Standard water model
WATER_FF = 'tip3p.xml' 

# Atom counts for identification: C18H35O2- (18C + 2O + 35H = 55 atoms)
STEARATE_ATOMS = 55
SODIUM_ATOMS = 1
WATER_ATOMS = 3

def parameterize_and_create_system(pdb_file_path):
    """
    Reads the system coordinates, separates solute and solvent, 
    parameterizes the solute using OpenFF (in-memory), and combines with solvent using Modeller.
    
    The function generates a ready-to-use OpenMM System object.
    """
    print(f"--- 1. Loading coordinates from {pdb_file_path} ---")
    if not os.path.exists(pdb_file_path):
        print(f"ERROR: PDB file not found at {pdb_file_path}. Please check your path.")
        return None, None, None

    # Load the structure using ParmEd to get coordinates and a basic structure
    try:
        full_structure = parmed.load_file(pdb_file_path)
    except Exception as e:
        print(f"Error loading PDB file with ParmEd: {e}")
        return None, None, None
        
    # Load the PDB into an OpenMM PDBFile object for full atom and residue lists
    pdb_file_obj = app.PDBFile(pdb_file_path)
    openmm_topology_input = pdb_file_obj.topology
    full_openmm_positions = pdb_file_obj.getPositions() # OpenMM coordinates
    
    # --- 2. Define Solute Molecules using SMILES ---
    stearate_ion_smiles = "CCCCCCCCCCCCCCCCCC(=O)[O-]"
    sodium_ion_smiles = "[Na+]"
    
    stearate_ion = Molecule.from_smiles(stearate_ion_smiles, allow_undefined_stereo=True)
    sodium_ion = Molecule.from_smiles(sodium_ion_smiles, allow_undefined_stereo=True)
    
    # Explicitly name the OpenFF molecules to help matching
    stearate_ion.name = "STL" 
    sodium_ion.name = "NA"
    
    unique_solute_molecules = [stearate_ion, sodium_ion]
    
    # --- 3. Identify and Separate Solute and Solvent Atom Indices ---
    print("--- 2. Separating Solute (STL, NA) and Solvent (HOH) ---")
    
    solute_atom_indices = []
    stearate_count = 0
    sodium_count = 0
    
    # Manually iterate over ParmEd structure residues to identify and collect solute indices
    for residue in full_structure.residues:
        num_atoms = len(residue.atoms)
        if num_atoms == STEARATE_ATOMS:
            solute_atom_indices.extend([atom.idx for atom in residue.atoms])
            stearate_count += 1
        elif num_atoms == SODIUM_ATOMS:
            solute_atom_indices.extend([atom.idx for atom in residue.atoms])
            sodium_count += 1
    
    # --- 4. Generate Corrected Solute Topology (in-memory) ---
    print("--- 3. Generating Corrected Solute Topology via OpenFF (in-memory) ---")
    
    # 4a. Create a list of the intended solute molecules in the correct order 
    # (matching the order of indices collected above).
    ordered_solute_molecules = ([stearate_ion] * stearate_count) + ([sodium_ion] * sodium_count)
    
    # 4b. Use OpenFF to create a guaranteed correct OpenFF Topology from the ordered molecules.
    openff_solute_topology = Topology.from_molecules(ordered_solute_molecules)

    # 4c. Convert the fixed OpenFF Topology back to an OpenMM Solute Topology.
    fixed_openmm_solute_topology = openff_solute_topology.to_openmm()
    
    # 4d. Extract the solute positions in the same order as the indices were collected
    solute_positions_nm = []
    
    # Get the positions in the base unit (nanometers) as a numpy array
    full_coords_nm = full_openmm_positions.value_in_unit(unit.nanometers)
    
    for idx in solute_atom_indices:
        # Append the array [x, y, z] for the solute atom
        solute_positions_nm.append(full_coords_nm[idx])

    # Convert the list of unit-less coordinates to a NumPy array and apply the unit
    solute_positions_array = np.array(solute_positions_nm) * unit.nanometers
    
    # --- 5. Rebuild Full System Topology using Modeller ---
    print("--- 4. Rebuilding Full System Topology with Fixed Solute and Water ---")
    
    # Initialize Modeller with the fixed solute topology and positions
    modeller = app.Modeller(fixed_openmm_solute_topology, solute_positions_array)
    
    # --- Manual Water Topology and Positions Generation ---
    water_topology = app.Topology()
    water_positions_list = []
    water_count = 0
    
    # Create a single chain for all water molecules
    water_chain = water_topology.addChain()

    # Iterate over the *input* topology to find water molecules
    for res in openmm_topology_input.residues():
        # Check atom count for water (HOH has 3 atoms)
        if len(list(res.atoms())) == WATER_ATOMS:
            water_count += 1
            
            # Add the residue and atoms to the new water topology
            # Use original residue name (HOH) and ID
            new_res = water_topology.addResidue("HOH", water_chain, res.id)
            
            # Temporary dict to store the newly created OpenMM Atom objects for bonding
            new_atoms = {}
            atom_indices = [atom.index for atom in res.atoms()]
            
            for idx, atom in zip(atom_indices, res.atoms()):
                # Add the atom to the new residue/topology and store the reference
                new_atom = water_topology.addAtom(atom.name, atom.element, new_res, atom.id)
                new_atoms[atom.name] = new_atom # Store by name (O, H1, H2)
                
                # Collect the position (unit-less)
                water_positions_list.append(full_coords_nm[idx])
                
            # --- CRITICAL: ADD BONDS TO WATER (Required for OpenMM SystemGenerator match) ---
            # TIP3P water: O bonded to H1 and H2
            if 'O' in new_atoms and 'H1' in new_atoms and 'H2' in new_atoms:
                water_topology.addBond(new_atoms['O'], new_atoms['H1'])
                water_topology.addBond(new_atoms['O'], new_atoms['H2'])


    # Convert the list of unit-less coordinates to a NumPy array and apply the unit
    water_positions_array = np.array(water_positions_list) * unit.nanometers

    # Add the manually constructed water topology and positions to the Modeller
    print(f"Adding {water_count} water residues to the system.")
    modeller.add(water_topology, water_positions_array)
    
    # Final Topology and Positions
    full_openmm_topology = modeller.topology
    final_positions = modeller.positions
    
    # --- 6. Prepare Final Topology (Renaming Residues for SystemGenerator) ---
    print("--- 5. Preparing Final Topology (Renaming Residues for SystemGenerator) ---")
    
    # Explicitly rename residues on the full OpenMM topology object
    current_stearate = 0
    current_sodium = 0
    current_water = 0
    
    for chain in full_openmm_topology.chains():
        for residue in chain.residues():
            # Check atom count to identify the molecule type
            num_atoms = len(list(residue.atoms())) 
            if num_atoms == STEARATE_ATOMS:
                residue.name = "STL" 
                current_stearate += 1
            elif num_atoms == SODIUM_ATOMS:
                residue.name = "NA"
                current_sodium += 1
            elif num_atoms == WATER_ATOMS:
                # Residue name is already HOH from step 5, but we ensure the count is correct
                residue.name = "HOH"
                current_water += 1
                
    print(f"Renamed {current_stearate} Stearate (STL), {current_sodium} Sodium (NA), {current_water} Water (HOH) residues in topology.")

    # --- 7. Initialize Final System Generator ---
    print("--- 6. Initializing Final System Generator ---")
    print(f"Using Solute FF: {OPENFF_FF}")
    print(f"Using Solvent FF: {WATER_FF}")
    
    # Final System Generator (handles combining FFs and water models)
    final_generator = SystemGenerator(
        forcefields=[WATER_FF], 
        small_molecule_forcefield=OPENFF_FF,
        molecules=unique_solute_molecules,
    )
    
    # --- 8. Create the final OpenMM System ---
    print("--- 7. Generating OpenMM System with parameters (This may take a moment) ---")
    
    # Generate the FINAL OpenMM System using the clean, full topology with no extra arguments
    openmm_system = final_generator.create_system(
        full_openmm_topology, # Use the OpenFF-corrected and Modeller-rebuilt topology
    )
    
    # --- 8.5. Manually Apply TIP3P Constraints (Crucial for rigid water) ---
    print("--- 7.5. Manually applying TIP3P constraints for HOH molecules ---")

    # TIP3P bond lengths (in nanometers)
    O_H_distance = 0.09572 * unit.nanometers
    H_H_distance = 0.15139 * unit.nanometers 
    constraints_added = 0

    for residue in full_openmm_topology.residues():
        if residue.name == "HOH":
            # Map atom names to OpenMM indices
            atoms = {atom.name: atom.index for atom in residue.atoms()}
            
            # Add the three geometric constraints required for SETTLE
            if all(name in atoms for name in ['O', 'H1', 'H2']):
                idx_O = atoms['O']
                idx_H1 = atoms['H1']
                idx_H2 = atoms['H2']

                openmm_system.addConstraint(idx_O, idx_H1, O_H_distance)
                openmm_system.addConstraint(idx_O, idx_H2, O_H_distance)
                openmm_system.addConstraint(idx_H1, idx_H2, H_H_distance)
                constraints_added += 3

    print(f"    -> Applied {constraints_added} constraints to water molecules.")


    # --- 9. Manually Apply Missing Simulation Settings ---
    print("--- 8. Manually applying PME and Box Vectors to the OpenMM System ---")
    
    # The box vectors must be set manually since the PDB does not contain them
    # Based on PACKMOL box size (110.0 Angstroms = 11.0 nm)
    box_size_nm = 11.0
    box_vector = om.Vec3(box_size_nm * unit.nanometers, 0, 0)
    openmm_system.setDefaultPeriodicBoxVectors(
        box_vector,
        om.Vec3(0, box_vector[0], 0),
        om.Vec3(0, 0, box_vector[0])
    )
    
    print("\n✅ Final System Parameterization Complete.")
    print("The OpenMM System object is ready for simulation.")
    
    # --- 10. Saving Final PDB coordinates ---
    # We save a final PDB file which can be used alongside the OpenMM System object
    with open('openmm_system.pdb', 'w') as f:
        # Use the final topology and positions from the Modeller
        app.PDBFile.writeFile(full_openmm_topology, final_positions, f, keepIds=True)
    
    print("Files saved:")
    print("- openmm_system.pdb (Initial coordinates for the OpenMM simulation)")

    # The GROMACS export section has been removed as it is not needed for OpenMM.
    # We return the key objects required for an OpenMM simulation run:
    return openmm_system, full_openmm_topology, final_positions

if __name__ == "__main__":
    
    # Check for required dependencies
    try:
        import openmmforcefields
        import parmed
        import numpy
    except ImportError:
        print("\nFATAL ERROR: The 'openmmforcefields', 'parmed', and 'numpy' packages are required.")
        print("Please install them: conda install -c conda-forge openmm openmmforcefields parmed numpy")
        exit()

    # The main function now returns the OpenMM objects directly
    openmm_system, openmm_topology, initial_positions = parameterize_and_create_system(INPUT_PDB)

    print("\n--- NEXT STEP: Run the OpenMM Simulation ---")
    print("The Python script has successfully generated the key objects:")
    print("1. 'openmm_system': The OpenMM System with all forces and parameters.")
    print("2. 'openmm_topology': The OpenMM Topology with residue/atom names.")
    print("3. 'initial_positions': The initial coordinates.")
    print("You can now use these objects to create an Integrator and Simulation object in OpenMM.")