"""Quick validation run for the generated OpenMM System.

This script imports the parameterization function and runs a short
minimization + 500-step Langevin dynamics to verify the system is runnable.

It assumes the following files exist in `src/system`:
 - system_coordinates.pdb (generated by PACKMOL)
 - openff-2.2.0.offxml and tip3p.xml available to SystemGenerator (installed)

This is intentionally small and conservative; change steps/integrator as needed.
"""
import sys
import time
from openmm import unit
import openmm as om
import openmm.app as app

# Import the local forcefields module. When this script is executed with CWD
# == src/system we can import the sibling module directly as `forcefields`.
# If the script is run from the repository root, fall back to the package-style import.
try:
    from forcefields import parameterize_and_create_system, INPUT_PDB
except Exception:
    from src.system.forcefields import parameterize_and_create_system, INPUT_PDB


def run_quick_validation(pdb_path=INPUT_PDB, nsteps=500):
    print("Running quick OpenMM validation run...")
    system, topology, positions = parameterize_and_create_system(pdb_path)
    if system is None:
        print("Parameterization failed; aborting quick run.")
        return 1

    # Small timestep and friction for stability
    temperature = 300.0 * unit.kelvin
    friction = 1.0 / unit.picoseconds
    timestep = 2.0 * unit.femtoseconds

    integrator = om.LangevinIntegrator(temperature, friction, timestep)

    # Prefer fast platforms if available; fall back to Reference
    try:
        platform = om.Platform.getPlatformByName('CUDA')
    except Exception:
        try:
            platform = om.Platform.getPlatformByName('CPU')
        except Exception:
            platform = om.Platform.getPlatformByName('Reference')

    simulation = app.Simulation(topology, system, integrator, platform)
    simulation.context.setPositions(positions)

    print("Minimizing...")
    simulation.minimizeEnergy()

    print(f"Running {nsteps} steps of Langevin dynamics...")
    start = time.time()
    simulation.step(nsteps)
    elapsed = time.time() - start

    state = simulation.context.getState(getEnergy=True)
    potential = state.getPotentialEnergy()
    kinetic = state.getKineticEnergy()

    print(f"Elapsed: {elapsed:.2f}s | Potential: {potential} | Kinetic: {kinetic}")
    return 0


if __name__ == '__main__':
    rc = run_quick_validation()
    sys.exit(rc)
