#!/usr/bin/env python3
"""Build a MARTINI coarse-grained system: generate .gro coordinates + .top topology."""
from __future__ import annotations

import tomllib
import numpy as np
from pathlib import Path

BOND_LENGTH = 0.47  # nm, standard MARTINI bond
RNG = np.random.default_rng(42)

# Bead names per molecule type (must match the ITP [atoms] sections)
BEAD_NAMES: dict[str, list[str]] = {
    # Saturated soaps
    "STR": ["COO", "C1A", "C1B", "C1C", "C1D"],
    "PAL": ["COO", "C1A", "C1B", "C1C", "C1D"],
    "MYR": ["COO", "C1A", "C1B", "C1C"],
    "LAU": ["COO", "C1A", "C1B", "C1C"],
    # Unsaturated soaps
    "OLE": ["COO", "C1A", "C3A", "C1B", "C1C"],
    "RIC": ["COO", "C1A", "C3A", "POH", "C1B"],
    # Counterion
    "NA+": ["NA"],
    # Solvents / polyols
    "W":   ["W"],
    "PGO": ["PG"],
    "ETH": ["ETH"],
    "GLY": ["GLY"],
    "SOR": ["S1", "S2"],
    "SUC": ["S1", "S2", "S3"],
}


def _random_direction() -> np.ndarray:
    """Uniform random unit vector on the sphere."""
    theta = np.arccos(1 - 2 * RNG.random())
    phi = 2 * np.pi * RNG.random()
    return np.array([np.sin(theta) * np.cos(phi),
                     np.sin(theta) * np.sin(phi),
                     np.cos(theta)])


def _place_chain(n_beads: int, box: np.ndarray) -> np.ndarray:
    """Place a linear chain of *n_beads* randomly in the box."""
    origin = RNG.random(3) * box
    if n_beads == 1:
        return origin.reshape(1, 3)
    direction = _random_direction()
    coords = np.array([origin + i * BOND_LENGTH * direction
                       for i in range(n_beads)])
    return coords % box  # wrap into PBC


def write_gro(molecules: list[dict], box: np.ndarray, path: Path) -> None:
    """Write a GROMACS .gro coordinate file."""
    total_beads = sum(m["count"] * m["n_beads"] for m in molecules)
    lines = [f"MARTINI CG system ({total_beads} beads)", f"{total_beads}"]

    atom_idx = 0
    res_idx = 0
    for mol in molecules:
        name = mol["name"]
        beads = BEAD_NAMES.get(name, [name[:3]] * mol["n_beads"])
        for _ in range(mol["count"]):
            res_idx += 1
            coords = _place_chain(mol["n_beads"], box)
            for j, (bead_name, xyz) in enumerate(zip(beads, coords)):
                atom_idx += 1
                # GRO format: %5d%-5s%5s%5d%8.3f%8.3f%8.3f
                res_num = res_idx % 100000
                atom_num = atom_idx % 100000
                lines.append(
                    f"{res_num:5d}{name:<5s}{bead_name:>5s}{atom_num:5d}"
                    f"{xyz[0]:8.3f}{xyz[1]:8.3f}{xyz[2]:8.3f}"
                )

    lines.append(f"   {box[0]:.5f}   {box[1]:.5f}   {box[2]:.5f}")
    path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {path}  ({total_beads} beads, {res_idx} molecules)")


def write_top(molecules: list[dict], system_name: str, path: Path) -> None:
    """Write a GROMACS .top topology file."""
    # Map molecule names to ITP filenames
    itp_map = {
        "STR": "stearate", "PAL": "palmitate", "MYR": "myristate",
        "LAU": "laurate", "OLE": "oleate", "RIC": "ricinoleate",
        "NA+": "sodium", "W": "water",
        "PGO": "pg", "ETH": "ethanol", "GLY": "glycerol",
        "SOR": "sorbitol", "SUC": "sucrose",
    }
    lines = [
        f'; Topology for {system_name}',
        f'; Generated by build.py',
        '',
        '#include "forcefield/martini_v2.2.itp"',
        '',
    ]
    seen = set()
    for mol in molecules:
        name = mol["name"]
        if name not in seen:
            itp = itp_map.get(name, name.lower())
            lines.append(f'#include "molecules/{itp}.itp"')
            seen.add(name)

    lines += [
        '',
        '[ system ]',
        system_name,
        '',
        '[ molecules ]',
        '; name  count',
    ]
    for mol in molecules:
        lines.append(f'{mol["name"]:<8s} {mol["count"]}')

    path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {path}")


def main():
    base = Path(__file__).parent
    with open(base / "config.toml", "rb") as f:
        cfg = tomllib.load(f)

    box = np.array(cfg["system"]["box"])
    molecules = cfg["molecules"]
    system_name = cfg["system"].get("name", "CG System")

    out = base / "output"
    out.mkdir(exist_ok=True)

    write_gro(molecules, box, out / "system.gro")
    write_top(molecules, system_name, out / "topol.top")

    total = sum(m["count"] * m["n_beads"] for m in molecules)
    print(f"\nSystem: {total} CG beads in {box[0]:.1f} x {box[1]:.1f} x {box[2]:.1f} nm box")
    print(f"Next: bash run.sh")


if __name__ == "__main__":
    main()
