#!/usr/bin/env python3
"""Build a MARTINI coarse-grained system: generate .gro coordinates + .top topology."""
from __future__ import annotations

import tomllib
import numpy as np
from pathlib import Path

BOND_LENGTH = 0.47  # nm, standard MARTINI bond
RNG = np.random.default_rng(42)

# Bead names per molecule type (must match the ITP [atoms] sections)
BEAD_NAMES: dict[str, list[str]] = {
    # Saturated soaps
    "STR": ["COO", "C1A", "C1B", "C1C", "C1D"],
    "PAL": ["COO", "C1A", "C1B", "C1C", "C1D"],
    "MYR": ["COO", "C1A", "C1B", "C1C"],
    "LAU": ["COO", "C1A", "C1B", "C1C"],
    # Unsaturated soaps
    "OLE": ["COO", "C1A", "C3A", "C1B", "C1C"],
    "RIC": ["COO", "C1A", "C3A", "POH", "C1B"],
    # Counterions
    "NA+": ["NA"],
    "K+":  ["K"],
    # Solvents / polyols
    "W":   ["W"],
    "PGO": ["PG"],
    "ETH": ["ETH"],
    "GLY": ["GLY"],
    "SOR": ["S1", "S2"],
    "SUC": ["S1", "S2", "S3"],
}

# Map molecule config names to ITP filenames
ITP_MAP = {
    "STR": "stearate", "PAL": "palmitate", "MYR": "myristate",
    "LAU": "laurate", "OLE": "oleate", "RIC": "ricinoleate",
    "NA+": "sodium", "K+": "potassium", "W": "water",
    "PGO": "pg", "ETH": "ethanol", "GLY": "glycerol",
    "SOR": "sorbitol", "SUC": "sucrose",
}

# Charge per molecule name (for auto-computing counterion counts)
CHARGE = {
    "LAU": -1, "MYR": -1, "PAL": -1, "STR": -1,
    "OLE": -1, "RIC": -1,
    "NA+": +1, "K+": +1,
}


def _random_direction() -> np.ndarray:
    theta = np.arccos(1 - 2 * RNG.random())
    phi = 2 * np.pi * RNG.random()
    return np.array([np.sin(theta) * np.cos(phi),
                     np.sin(theta) * np.sin(phi),
                     np.cos(theta)])


def _place_chain(n_beads: int, box: np.ndarray) -> np.ndarray:
    origin = RNG.random(3) * box
    if n_beads == 1:
        return origin.reshape(1, 3)
    direction = _random_direction()
    coords = np.array([origin + i * BOND_LENGTH * direction
                       for i in range(n_beads)])
    return coords % box


def _compute_counterion_counts(solutes: list[dict],
                               counterions: list[dict]) -> list[dict]:
    """Compute counterion molecule counts from solute charges and fractions."""
    total_charge = sum(
        m["count"] * CHARGE.get(m["name"], 0) for m in solutes
    )
    total_needed = abs(total_charge)

    if total_needed == 0:
        return []

    # Validate fractions
    frac_sum = sum(ci["fraction"] for ci in counterions)
    if abs(frac_sum - 1.0) > 0.01:
        raise ValueError(
            f"Counterion fractions must sum to 1.0, got {frac_sum:.3f}")

    result = []
    assigned = 0
    for i, ci in enumerate(counterions):
        if i == len(counterions) - 1:
            n = total_needed - assigned
        else:
            n = round(total_needed * ci["fraction"])
        n_beads = len(BEAD_NAMES.get(ci["name"], [ci["name"]]))
        result.append({
            "name": ci["name"],
            "count": n,
            "n_beads": n_beads,
            "is_chain": False,
        })
        assigned += n
        print(f"  counterion {ci['name']}: {n} (fraction {ci['fraction']:.0%})")

    return result


def write_gro(molecules: list[dict], box: np.ndarray, path: Path) -> None:
    total_beads = sum(m["count"] * m["n_beads"] for m in molecules)
    lines = [f"MARTINI CG system ({total_beads} beads)", f"{total_beads}"]

    atom_idx = 0
    res_idx = 0
    for mol in molecules:
        name = mol["name"]
        beads = BEAD_NAMES.get(name, [name[:3]] * mol["n_beads"])
        for _ in range(mol["count"]):
            res_idx += 1
            coords = _place_chain(mol["n_beads"], box)
            for j, (bead_name, xyz) in enumerate(zip(beads, coords)):
                atom_idx += 1
                res_num = res_idx % 100000
                atom_num = atom_idx % 100000
                lines.append(
                    f"{res_num:5d}{name:<5s}{bead_name:>5s}{atom_num:5d}"
                    f"{xyz[0]:8.3f}{xyz[1]:8.3f}{xyz[2]:8.3f}"
                )

    lines.append(f"   {box[0]:.5f}   {box[1]:.5f}   {box[2]:.5f}")
    path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {path}  ({total_beads} beads, {res_idx} molecules)")


def write_top(molecules: list[dict], system_name: str, path: Path) -> None:
    lines = [
        f'; Topology for {system_name}',
        f'; Generated by build.py',
        '',
        '#include "forcefield/martini_v2.2.itp"',
        '',
    ]
    seen = set()
    for mol in molecules:
        name = mol["name"]
        if name not in seen:
            itp = ITP_MAP.get(name, name.lower())
            lines.append(f'#include "molecules/{itp}.itp"')
            seen.add(name)

    lines += [
        '',
        '[ system ]',
        system_name,
        '',
        '[ molecules ]',
        '; name  count',
    ]
    for mol in molecules:
        lines.append(f'{mol["name"]:<8s} {mol["count"]}')

    path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {path}")


def main():
    base = Path(__file__).parent
    with open(base / "config.toml", "rb") as f:
        cfg = tomllib.load(f)

    box = np.array(cfg["system"]["box"])
    system_name = cfg["system"].get("name", "CG System")

    # Separate solutes, solvents, and counterions
    solutes = cfg.get("solutes", [])
    solvents = cfg.get("solvents", [])
    ci_specs = cfg.get("counterions", [{"name": "NA+", "fraction": 1.0}])

    # Build the ordered molecule list: solutes -> counterions -> solvents
    all_molecules = list(solutes)
    all_molecules.extend(_compute_counterion_counts(solutes, ci_specs))
    all_molecules.extend(solvents)

    out = base / "output"
    out.mkdir(exist_ok=True)

    write_gro(all_molecules, box, out / "system.gro")
    write_top(all_molecules, system_name, out / "topol.top")

    total = sum(m["count"] * m["n_beads"] for m in all_molecules)
    print(f"\nSystem: {total} CG beads in "
          f"{box[0]:.1f} x {box[1]:.1f} x {box[2]:.1f} nm box")
    print(f"Next: bash run.sh")


if __name__ == "__main__":
    main()
